spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/inventorydb
    username: inventory
    password: inventorypass
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  jwt:
    secret: "a_super_long_random_secret_string_at_least_32_chars"
  kafka:
    ordersTopic: "orders.events"