### Register
POST http://localhost:8081/auth/register
Content-Type: application/json

{"email":"test2@example.com","password":"Password123!"}

### Login
POST http://localhost:8081/auth/login
Content-Type: application/json

{"email":"test2@example.com","password":"Password123!"}

### Create Order
POST http://localhost:8082/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwb3J0Zm9saW8tcGxhdGZvcm0iLCJzdWIiOiI1ZDg2OWNjMC03ODkwLTQ3MjQtYWM0OC04MjY0MzE3MTc4OTUiLCJleHAiOjE3NzAzNTkwNTYsImlhdCI6MTc3MDM1NzI1NiwiZW1haWwiOiJ0ZXN0MkBleGFtcGxlLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIn0.o4oyewP0gYN8qGYC19FFLBmkuuZUUoR0liZx385HZHY
