### Register
POST http://localhost:8081/auth/register
Content-Type: application/json

{"email":"test2@example.com","password":"Password123!"}

### Login
POST http://localhost:8081/auth/login
Content-Type: application/json

{"email":"test2@example.com","password":"Password123!"}

### Create Order
POST http://localhost:8082/orders
//Paste Token returned from Login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJwb3J0Zm9saW8tcGxhdGZvcm0iLCJzdWIiOiJkYWUwOGJkNC1jZjQ1LTRkNWUtYTgwNS00M2UwNGZkMWMyODgiLCJleHAiOjE3NzIwMTkwODEsImlhdCI6MTc3MjAxNzI4MSwiZW1haWwiOiJ0ZXN0MkBleGFtcGxlLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIn0.zlbA1B2svzDgR6CYFQ0MChOV7KZ1N620WyfNmTcyQro
