spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/shippingdb
    username: shipping
    password: shippingpass
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shipping-service
      auto-offset-reset: earliest
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    ordersTopic: "orders.events"