spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ordersdb
    username: orders
    password: orderspass
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092

app:
  jwt:
    secret: "a_super_long_random_secret_string_at_least_32_chars"